<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jomaica Lei">

<title>Data Translation Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="DTC_files/libs/clipboard/clipboard.min.js"></script>
<script src="DTC_files/libs/quarto-html/quarto.js"></script>
<script src="DTC_files/libs/quarto-html/popper.min.js"></script>
<script src="DTC_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="DTC_files/libs/quarto-html/anchor.min.js"></script>
<link href="DTC_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="DTC_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="DTC_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="DTC_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="DTC_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="DTC_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="DTC_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Translation Challenge</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jomaica Lei </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="amazon" class="level2">
<h2 class="anchored" data-anchor-id="amazon">Amazon</h2>
<p>In this assignment, you will be given a dataset of <a href="https://a1029-70891957.cluster88.canvas-user-content.com/courses/1029~1615651/files/1029~70891957/course%20files/amazon.com">Amazon</a> sales of technology products placed over several months in 2019 in a select number of urban ZIP codes.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<section id="sales_data.rdata" class="level3">
<h3 class="anchored" data-anchor-id="sales_data.rdata">sales_data.Rdata</h3>
<p><code>sales_data.Rdata</code> can be loaded in using the <code>import()</code> function from the <strong>rio</strong> package. Put the file in your working directory (generally, the same folder you’ve saved your .RMD file in; you can then go Session →→ Set Working Directory to be sure), and load it in:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rio)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sales <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="st">'sales_data.Rdata'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `trust` argument of `import()` should be explicit for serialization formats
as of rio 1.0.3.
ℹ Missing `trust` will be set to FALSE by default for RData in 2.0.0.
ℹ The deprecated feature was likely used in the rio package.
  Please report the issue at &lt;https://github.com/gesistsa/rio/issues&gt;.</code></pre>
</div>
</div>
<p>Let’s take a quick look:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Product Quantity PriceEach            DateTime       Date
1       USB-C Charging Cable        2     11.95 2019-04-19 08:46:00 2019-04-19
2 Bose SoundSport Headphones        1     99.99 2019-04-07 22:30:00 2019-04-07
3               Google Phone        1       600 2019-04-12 14:38:00 2019-04-12
4           Wired Headphones        1     11.99 2019-04-12 14:38:00 2019-04-12
5           Wired Headphones        1     11.99 2019-04-30 09:27:00 2019-04-30
6       USB-C Charging Cable        1     11.95 2019-04-29 13:03:00 2019-04-29
    ZIP State          City
1 75001    TX        Dallas
2 02215    MA        Boston
3 90001    CA   Los Angeles
4 90001    CA   Los Angeles
5 90001    CA   Los Angeles
6 94016    CA San Francisco</code></pre>
</div>
</div>
<p>This data set contains eight variables:</p>
<ul>
<li><p><code>Product</code>, the product that has been ordered</p></li>
<li><p><code>Quantity</code>, how many of the product was ordered (note this is a string, you’ll want to fix that!)</p></li>
<li><p><code>PriceEach</code>, the price of each item (note this is a string, you’ll want to fix that!)</p></li>
<li><p><code>DateTime</code> and <code>Date</code>, when the order was placed. <code>DateTime</code> includes both day and time-of-day when the order was placed, while <code>Date</code> is just the date</p></li>
<li><p><code>ZIP</code>, the ZIP code where the order was sent to</p></li>
<li><p><code>State</code> and <code>City</code>, the city and state where the order was sent to</p></li>
</ul>
<p>Let’s look at some descriptive statistics:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vtable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: kableExtra</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vtable</span>(sales, <span class="at">lush =</span> <span class="cn">TRUE</span>, <span class="at">factor.limit =</span> <span class="dv">9</span>, <span class="at">char.values =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>sales</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Name</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Class</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Values</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Missing</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Summary</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Product</td>
<td style="text-align: left;">character</td>
<td style="text-align: left;">'20in Monitor' '27in 4K Gaming Monitor' '27in FHD Monitor' '34in Ultrawide Monitor' 'AA Batteries (4-pack)' 'AAA Batteries (4-pack)' 'Apple Airpods Headphones' 'Bose SoundSport Headphones' 'Flatscreen TV' and 10 more</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">nuniq: 19</td>
</tr>
<tr class="even">
<td style="text-align: left;">Quantity</td>
<td style="text-align: left;">character</td>
<td style="text-align: left;">'1' '2' '3' '4' '5' '6' '7' '8' '9'</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">nuniq: 9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PriceEach</td>
<td style="text-align: left;">character</td>
<td style="text-align: left;">'109.99' '11.95' '11.99' '14.95' '149.99' '150' '150.0' '1700' '1700.0' and 14 more</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">nuniq: 23</td>
</tr>
<tr class="even">
<td style="text-align: left;">DateTime</td>
<td style="text-align: left;">POSIXct</td>
<td style="text-align: left;">Time: 2019-01-01 03:07:00 to 2020-01-01 05:13:00</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">median: 2019-07-17 20:40:30, nuniq: 142395</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Date</td>
<td style="text-align: left;">Date</td>
<td style="text-align: left;">Time: 2019-01-01 to 2020-01-01</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">median: 2019-07-17, nuniq: 366</td>
</tr>
<tr class="even">
<td style="text-align: left;">ZIP</td>
<td style="text-align: left;">character</td>
<td style="text-align: left;">'02215' '04101' '10001' '30301' '73301' '75001' '90001' '94016' '97035' and 1 more</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">nuniq: 10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">State</td>
<td style="text-align: left;">character</td>
<td style="text-align: left;">'CA' 'GA' 'MA' 'ME' 'NY' 'OR' 'TX' 'WA'</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">nuniq: 8</td>
</tr>
<tr class="even">
<td style="text-align: left;">City</td>
<td style="text-align: left;">character</td>
<td style="text-align: left;">'Atlanta' 'Austin' 'Boston' 'Dallas' 'Los Angeles' 'New York City' 'Portland' 'San Francisco' 'Seattle'</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">nuniq: 9</td>
</tr>
</tbody>
</table>


</div>
</div>
<ul>
<li><p>We can first see that <code>Quantity</code> and <code>PriceEach</code> are both stored as character variables, we’ll have to do something about that (hint: <code>as.numeric()</code>).</p></li>
<li><p>We can also see that the data covers from January 2019 through December 2019</p></li>
<li><p>We also see that a limited set of only 9 ZIP codes are covered, and all of them are in urban areas (Atlanta, Austin, etc.).</p></li>
<li><p>There is only one ZIP per city, and cities generally have many ZIP codes, so we are only covering a single part of each city. For example, that Seattle ZIP code is for a part of downtown Seattle. You can put the ZIP code into Google Maps if you want to see specifically where each ZIP is</p></li>
<li><p>There’s a Portland in Oregon and a Portland in Maine</p></li>
<li><p>If you want to work with the time element of that <code>DateTime</code> variable, note that you can pull out information like the hour and minute with <strong>lubridate</strong> functions like <code>hour()</code> and <code>minute()</code>. Also, as always, keep other <strong>lubridate</strong> functions in mind that might be handy, like <code>floor_date()</code> to “round” dates to the first day in that week/month/etc.</p></li>
</ul>
<p>Finally, we see in the <code>Product</code> variable that we are tracking 19 different products, not the entire lineup of everything Amazon sells. If you look at that list (perhaps with <code>table()</code> or <code>unique()</code>) you’ll see that this covers a few different kinds of products, including monitors, laptops, smartphones, and batteries. If you want to analyze some things as a group you may need to use some of the <strong>stringr</strong> functions we used (or perhaps <code>case_when()</code>) to pull information from the product names.</p>
</section>
<section id="zip_info.csv" class="level3">
<h3 class="anchored" data-anchor-id="zip_info.csv">zip_info.csv</h3>
<p><code>zip_info.csv</code> can be read in using the <code>import()</code> function. Put the file in your working directory (generally, the same folder you’ve saved your .QMD file in; you can then go Session →→ Set Working Directory to be sure), and load it in:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>zip_info <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="st">'zip_info.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s take a quick look. This file contains information on the population of the ZIP codes included in our data. Numbers come from the 2018 American Community Survey (ACS) estimates, i.e.&nbsp;they use five years of ACS data from 2014-2018 to estimate the 2018 numbers:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vtable</span>(zip_info, <span class="at">lush =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>zip_info</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Name</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Class</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Values</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Missing</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Summary</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ZIP</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">Num: 2215 to 98101</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">mean: 57407.3, sd: 40907.601, nuniq: 10</td>
</tr>
<tr class="even">
<td style="text-align: left;">TotalPopulation</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">Num: 12792 to 58975</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">mean: 26051.6, sd: 12885.755, nuniq: 10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MedianHHIncome</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">Num: 46309 to 119370</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">mean: 81151, sd: 25319.33, nuniq: 10</td>
</tr>
<tr class="even">
<td style="text-align: left;">PCIncome</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">Num: 14814 to 100364</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">mean: 57085.4, sd: 28034.787, nuniq: 10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MedianAge</td>
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">Num: 21.6 to 44.3</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">mean: 34.02, sd: 6.243, nuniq: 10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race_White</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">Num: 9231 to 22921</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">mean: 16140.6, sd: 5012.111, nuniq: 10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Race_Black</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">Num: 459 to 5483</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">mean: 2179.9, sd: 1366.307, nuniq: 10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race_American_Indian</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">Num: 148 to 802</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">mean: 426.3, sd: 229.788, nuniq: 10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Race_Asian</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">Num: 173 to 10134</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">mean: 3238.9, sd: 3245.489, nuniq: 10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race_Pacific_Islander</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">Num: 0 to 237</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">mean: 71.3, sd: 81.024, nuniq: 9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Race_Other</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">Num: 181 to 30491</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">mean: 5003.8, sd: 9745.687, nuniq: 10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ethnicity_Hispanic</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">Num: 609 to 53085</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">mean: 9223, sd: 16630.268, nuniq: 10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Citizens</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">Num: 10432 to 24069</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">mean: 17171.8, sd: 4595.578, nuniq: 10</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>What we see here are:</p>
<ul>
<li><p><code>ZIP</code>, which is a ZIP code we can use to join this data set with the <code>sales</code> data</p></li>
<li><p><code>TotalPopulation</code>, which is the population in that ZIP code</p></li>
<li><p><code>MedianHHIncome</code>, which is the median annual household income in that ZIP. Household income calculates the total income from everyone in a given household, and then finds the median household (Income statistics use 2020 ACS instead of 2018)</p></li>
<li><p><code>PCIncome</code>, which is the annual per-capita (i.e.&nbsp;per-person) income in that ZIP. Per-capita income sums up all the income earned by everyone in the ZIP, and then divides it by the number of people in that ZIP (which may include a lot of non-earners, or children) (Income statistics use 2020 ACS instead of 2018)</p></li>
<li><p><code>MedianAge</code>, the median age of people in the ZIP code</p></li>
<li><p><code>Race_*</code> variables, the number of people of each broad-category race in that ZIP code. Note that races are not mutually exclusive. Someone who is, for example, both White and Asian will be counted once as White and once as Asian</p></li>
<li><p><code>Ethnicity_Hispanic</code>, which is the number of people who are Hispanic in the ZIP code. Ethnicity can overlap with any race, so someone who is, for example, both Hispanic and Black will be counted once as Hispanic and once as Black</p></li>
<li><p><code>Citizens</code>, which is the number of US citizens living in the ZIP code</p></li>
</ul>
<p>Some notes about this data:</p>
<ul>
<li><p>You can get the proportion of the ZIP code that is White/Black/Hispanic/Citizen/etc. by dividing that value by the <code>TotalPopulation</code></p></li>
<li><p>After you do your join with the sales data, check to make sure the join works correctly! Some of those ZIP codes have leading 0s which can sometimes be a problem (tip: convert everything to numeric, or use <code>str_pad()</code> in <strong>stringr</strong> to make the ZIPs five-digit-long strings, with leading 0s)</p></li>
<li><p>Using this file is not required; you could do everything with the <code>sales</code> data alone and ignore this if you want</p></li>
</ul>
</section>
<section id="packages-and-libraries" class="level3">
<h3 class="anchored" data-anchor-id="packages-and-libraries">1. Packages and Libraries</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter()     masks stats::filter()
✖ dplyr::group_rows() masks kableExtra::group_rows()
✖ dplyr::lag()        masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'scales'

The following object is masked from 'package:purrr':

    discard

The following object is masked from 'package:readr':

    col_factor</code></pre>
</div>
</div>
</section>
<section id="load-the-datasets" class="level3">
<h3 class="anchored" data-anchor-id="load-the-datasets">2. Load the Datasets</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set wd + load datasets</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>zip_info <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"zip_info.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 10 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (13): ZIP, TotalPopulation, MedianHHIncome, PCIncome, MedianAge, Race_Wh...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>sales <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"sales.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 185950 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (4): Product, ZIP, State, City
dbl  (2): Quantity, PriceEach
dttm (1): DateTime
date (1): Date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="data-processing" class="level3">
<h3 class="anchored" data-anchor-id="data-processing">3. Data Processing</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert ZIP columns to character type</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>zip_info <span class="ot">&lt;-</span> zip_info <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ZIP =</span> <span class="fu">as.character</span>(ZIP))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>sales <span class="ot">&lt;-</span> sales <span class="sc">%&gt;%</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ZIP =</span> <span class="fu">as.character</span>(ZIP))</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert DateTime to date format and extract date and month-year</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>sales <span class="ot">&lt;-</span> sales <span class="sc">%&gt;%</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DateTime =</span> <span class="fu">ymd_hms</span>(DateTime),</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">Date =</span> <span class="fu">as_date</span>(DateTime),</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">MonthYear =</span> <span class="fu">floor_date</span>(DateTime, <span class="st">"month"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `mutate()`.
ℹ In argument: `DateTime = ymd_hms(DateTime)`.
Caused by warning:
!  82 failed to parse.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge sales data with zip_info</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>merged_data <span class="ot">&lt;-</span> sales <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(zip_info, <span class="at">by =</span> <span class="st">"ZIP"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exploratory-data-analysis" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis">4. Exploratory Data Analysis</h3>
<ul>
<li><p>Look at summary statistics of key variables.</p></li>
<li><p>Distribution of sales across different ZIP codes.</p></li>
</ul>
<!-- -->
<ul>
<li><p>Popular products and their sales patterns.</p></li>
<li><p>Temporal analysis of sales (e.g., sales trends over time).</p></li>
<li><p>Relationship between sales and demographic factors.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics for zip_info and sales</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>zip_info_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(zip_info)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(zip_info_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     ZIP            TotalPopulation MedianHHIncome      PCIncome     
 Length:10          Min.   :12792   Min.   : 46309   Min.   : 14814  
 Class :character   1st Qu.:18670   1st Qu.: 59614   1st Qu.: 39644  
 Mode  :character   Median :24656   Median : 84555   Median : 53114  
                    Mean   :26052   Mean   : 81151   Mean   : 57085  
                    3rd Qu.:27922   3rd Qu.:100026   3rd Qu.: 79410  
                    Max.   :58975   Max.   :119370   Max.   :100364  
   MedianAge       Race_White      Race_Black   Race_American_Indian
 Min.   :21.60   Min.   : 9231   Min.   : 459   Min.   :148.0       
 1st Qu.:30.38   1st Qu.:13021   1st Qu.:1502   1st Qu.:268.8       
 Median :35.25   Median :15981   Median :2038   Median :315.0       
 Mean   :34.02   Mean   :16141   Mean   :2180   Mean   :426.3       
 3rd Qu.:37.30   3rd Qu.:19960   3rd Qu.:2571   3rd Qu.:606.2       
 Max.   :44.30   Max.   :22921   Max.   :5483   Max.   :802.0       
   Race_Asian      Race_Pacific_Islander   Race_Other      Ethnicity_Hispanic
 Min.   :  173.0   Min.   :  0.0         Min.   :  181.0   Min.   :  609     
 1st Qu.:  744.8   1st Qu.: 12.0         1st Qu.:  295.2   1st Qu.: 1216     
 Median : 2198.5   Median : 42.5         Median :  854.0   Median : 3077     
 Mean   : 3238.9   Mean   : 71.3         Mean   : 5003.8   Mean   : 9223     
 3rd Qu.: 5303.5   3rd Qu.: 90.0         3rd Qu.: 1980.8   3rd Qu.: 3548     
 Max.   :10134.0   Max.   :237.0         Max.   :30491.0   Max.   :53085     
    Citizens    
 Min.   :10432  
 1st Qu.:13910  
 Median :18034  
 Mean   :17172  
 3rd Qu.:19745  
 Max.   :24069  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>sales_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(sales)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sales_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Product             Quantity       PriceEach      
 Length:185950      Min.   :1.000   Min.   :   2.99  
 Class :character   1st Qu.:1.000   1st Qu.:  11.95  
 Mode  :character   Median :1.000   Median :  14.95  
                    Mean   :1.124   Mean   : 184.40  
                    3rd Qu.:1.000   3rd Qu.: 150.00  
                    Max.   :9.000   Max.   :1700.00  
                                                     
    DateTime                           Date                ZIP           
 Min.   :2019-01-01 03:07:00.00   Min.   :2019-01-01   Length:185950     
 1st Qu.:2019-04-16 21:08:45.00   1st Qu.:2019-04-16   Class :character  
 Median :2019-07-17 20:36:30.00   Median :2019-07-17   Mode  :character  
 Mean   :2019-07-18 21:54:36.96   Mean   :2019-07-18                     
 3rd Qu.:2019-10-26 08:14:00.00   3rd Qu.:2019-10-26                     
 Max.   :2020-01-01 05:13:00.00   Max.   :2020-01-01                     
 NA's   :82                       NA's   :82                             
    State               City             MonthYear                     
 Length:185950      Length:185950      Min.   :2019-01-01 00:00:00.00  
 Class :character   Class :character   1st Qu.:2019-04-01 00:00:00.00  
 Mode  :character   Mode  :character   Median :2019-07-01 00:00:00.00  
                                       Mean   :2019-07-03 12:45:27.72  
                                       3rd Qu.:2019-10-01 00:00:00.00  
                                       Max.   :2020-01-01 00:00:00.00  
                                       NA's   :82                      </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Distribution of Sales by Zipcode</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>sales_by_zip <span class="ot">&lt;-</span> sales <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(ZIP, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Sales =</span> n)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the sales distribution by ZIP code</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(merged_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 21
  Product    Quantity PriceEach DateTime            Date       ZIP   State City 
  &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt; &lt;dttm&gt;              &lt;date&gt;     &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;
1 USB-C Cha…        2      12.0 2019-04-19 08:46:00 2019-04-19 75001 TX    Dall…
2 Bose Soun…        1     100.  2019-04-07 22:30:00 2019-04-07 02215 MA    Bost…
3 Google Ph…        1     600   2019-04-12 14:38:00 2019-04-12 90001 CA    Los …
4 Wired Hea…        1      12.0 2019-04-12 14:38:00 2019-04-12 90001 CA    Los …
5 Wired Hea…        1      12.0 2019-04-30 09:27:00 2019-04-30 90001 CA    Los …
6 USB-C Cha…        1      12.0 2019-04-29 13:03:00 2019-04-29 94016 CA    San …
# ℹ 13 more variables: MonthYear &lt;dttm&gt;, TotalPopulation &lt;dbl&gt;,
#   MedianHHIncome &lt;dbl&gt;, PCIncome &lt;dbl&gt;, MedianAge &lt;dbl&gt;, Race_White &lt;dbl&gt;,
#   Race_Black &lt;dbl&gt;, Race_American_Indian &lt;dbl&gt;, Race_Asian &lt;dbl&gt;,
#   Race_Pacific_Islander &lt;dbl&gt;, Race_Other &lt;dbl&gt;, Ethnicity_Hispanic &lt;dbl&gt;,
#   Citizens &lt;dbl&gt;</code></pre>
</div>
</div>
<ul>
<li><p><strong>ZIP Info Summary: <code>zip_info_summary</code></strong></p>
<ul>
<li>Provides a detailed overview of the demographic data, including population, income, age, and racial composition for each ZIP code.</li>
</ul></li>
<li><p><strong>Sales Summary:</strong> <code>sales_summary</code></p>
<ul>
<li>Offers a glimpse into the overall sales data, including the number of products sold and price details.</li>
</ul></li>
<li><p><strong>Sales Distribution by ZIP Code:</strong> <code>sales_by_zip</code></p>
<ul>
<li>Shows the number of sales transactions for each ZIP code, which can help identify areas with higher sales activity.</li>
</ul></li>
<li><p><strong>Merged Data: <code>merged_data</code></strong></p>
<ul>
<li>Combines sales data with demographic information, enabling deeper analysis of how demographics might influence sales patterns.</li>
</ul></li>
</ul>
</section>
<section id="visualization" class="level3">
<h3 class="anchored" data-anchor-id="visualization">5. Visualization</h3>
<ul>
<li><p><strong>Sales Trends Over Time:</strong></p>
<ul>
<li>Analyze and visualize sales trends over different time periods (e.g., daily, monthly).</li>
</ul></li>
<li><p><strong>Popular Products Analysis:</strong></p>
<ul>
<li>Identify and visualize the most popular products and their sales distribution across different ZIP codes.</li>
</ul></li>
<li><p><strong>Demographic Influence:</strong></p>
<ul>
<li>Explore and visualize the relationship between sales and demographic factors such as income, age, and population.</li>
</ul></li>
<li><p><strong>Sales by City and State:</strong></p>
<ul>
<li>Visualize sales distribution across different cities and states to identify regional trends.</li>
</ul></li>
<li><p><strong>Product Sales by Time</strong>:</p>
<ul>
<li>Analyze how the sales of top products vary over time to identify any seasonal or periodic trends.</li>
</ul></li>
</ul>
<section id="sales-trend-over-time" class="level4">
<h4 class="anchored" data-anchor-id="sales-trend-over-time">5.1 Sales Trend Over Time</h4>
<p>Visualize sales trends over time to identify any patterns or spikes in sales activity. (Daily, Monthly)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Daily sales trend</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>daily_sales <span class="ot">&lt;-</span> sales <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Date) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Sales =</span> <span class="fu">n</span>())</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(daily_sales, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> Sales)) <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Daily Sales Trend"</span>, <span class="at">x =</span> <span class="st">"Date"</span>, <span class="at">y =</span> <span class="st">"Number of Sales"</span>) <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>   <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DTC_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Monthly sales trend</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>monthly_sales <span class="ot">&lt;-</span> sales <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(MonthYear) <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Sales =</span> <span class="fu">n</span>())</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(monthly_sales, <span class="fu">aes</span>(<span class="at">x =</span> MonthYear, <span class="at">y =</span> Sales)) <span class="sc">+</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Monthly Sales Trend"</span>, <span class="at">x =</span> <span class="st">"Month-Year"</span>, <span class="at">y =</span> <span class="st">"Number of Sales"</span>) <span class="sc">+</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>   <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DTC_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>Daily Sales Trend:</strong></p>
<ul>
<li>The line plot shows the fluctuation of sales on a daily basis. There may be visible peaks or troughs which could correlate with specific events, holidays, or promotional periods.</li>
</ul></li>
<li><p><strong>Monthly Sales Trend:</strong></p>
<ul>
<li><p>The monthly trend provides a broader view of sales activity over time, helping to identify any long-term trends or seasonal patterns.</p></li>
<li><p>A noticeable increase in sales during the holiday season in December.</p></li>
</ul></li>
</ul>
</section>
<section id="popular-product-analysis" class="level4">
<h4 class="anchored" data-anchor-id="popular-product-analysis">5.2 Popular Product Analysis</h4>
<p>Identify the top-selling products and visualize their sales distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Top-selling products</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>top_products <span class="ot">&lt;-</span> sales <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Product, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="dv">10</span>, n)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(top_products, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Product, n), <span class="at">y =</span> n, <span class="at">fill =</span> n)) <span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="fu">dollar_format</span>(<span class="at">scale =</span> <span class="dv">1</span>, <span class="at">suffix =</span> <span class="st">"K"</span>)) <span class="sc">+</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"lightblue"</span>, <span class="at">high =</span> <span class="st">"darkblue"</span>) <span class="sc">+</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Top-Selling Products"</span>, <span class="at">x =</span> <span class="st">"Product"</span>, <span class="at">y =</span> <span class="st">"Number of Sales"</span>) <span class="sc">+</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>   <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DTC_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Top-Selling Products:</strong></p>
<ul>
<li><p>The bar chart highlights the most popular products based on the number of sales from darkest to lightest color emphasizing sales. This can help identify key products driving revenue. (Focus on high-demand items)</p></li>
<li><p>The top products by sales volume are identified, e.g., “USB-C Charging Cable” and “Bose SoundSport Headphones”.</p></li>
</ul>
</section>
<section id="demographic-influence" class="level4">
<h4 class="anchored" data-anchor-id="demographic-influence">5.3 <strong>Demographic Influence</strong></h4>
<p>Explore and visualize the relationship between sales and demographic factors such as median household income and total population.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sales vs Median Household Income</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(merged_data, <span class="fu">aes</span>(<span class="at">x =</span> MedianHHIncome, <span class="at">y =</span> Quantity, <span class="at">color =</span> Product)) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sales vs Median Household Income"</span>, <span class="at">x =</span> <span class="st">"Median Household Income"</span>, <span class="at">y =</span> <span class="st">"Quantity Sold"</span>) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 22389 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DTC_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sales vs Total Population</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(merged_data, <span class="fu">aes</span>(<span class="at">x =</span> TotalPopulation, <span class="at">y =</span> Quantity, <span class="at">color =</span> Product)) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sales vs Total Population"</span>, <span class="at">x =</span> <span class="st">"Total Population"</span>, <span class="at">y =</span> <span class="st">"Quantity Sold"</span>) <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 22389 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DTC_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>Sales versus Median Household Income:</strong></p>
<ul>
<li><p>The scatter plot shows the relationship between the quantity of products sold and the median household income in different ZIP codes. Different colors represent different products. (This can reveal purchasing power and target markets)</p></li>
<li><p>Higher sales in ZIP codes with higher median household income.</p></li>
</ul></li>
<li><p><strong>Sales versus Total Population:</strong></p>
<ul>
<li><p>This scatter plot illustrates how the quantity of products sold correlates with the total population in various ZIP codes which helps us understand market size and potential.</p></li>
<li><p>Densely populated areas showing higher sales volumes.5.4 Sales Distribution by ZIP Code and City</p></li>
</ul></li>
</ul>
<p>Visualize how sales are distributed across different ZIP codes and cities.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sales distribution by ZIP code</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>sales_by_zip <span class="ot">&lt;-</span> sales <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(ZIP, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sales_by_zip, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(ZIP, n), <span class="at">y =</span> n, <span class="at">fill =</span> n)) <span class="sc">+</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="fu">dollar_format</span>(<span class="at">scale =</span> <span class="dv">1</span>, <span class="at">suffix =</span> <span class="st">"K"</span>)) <span class="sc">+</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"lightgreen"</span>, <span class="at">high =</span> <span class="st">"darkgreen"</span>) <span class="sc">+</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sales Distribution by ZIP Code"</span>, <span class="at">x =</span> <span class="st">"ZIP Code"</span>, <span class="at">y =</span> <span class="st">"Number of Sales"</span>) <span class="sc">+</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DTC_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sales distribution by city</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>sales_by_city <span class="ot">&lt;-</span> sales <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(City, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sales_by_city, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(City, n), <span class="at">y =</span> n, <span class="at">fill =</span> n)) <span class="sc">+</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="fu">dollar_format</span>(<span class="at">scale =</span> <span class="dv">1</span>, <span class="at">suffix =</span> <span class="st">"K"</span>)) <span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"lightgreen"</span>, <span class="at">high =</span> <span class="st">"darkgreen"</span>) <span class="sc">+</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sales Distribution by City"</span>, <span class="at">x =</span> <span class="st">"City"</span>, <span class="at">y =</span> <span class="st">"Number of Sales"</span>) <span class="sc">+</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DTC_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>Sales Distribution by ZIP Code:</strong></p>
<ul>
<li><p>The count plot shows how sales are distributed across different ZIP codes, highlighting areas with higher or lower sales activity.</p></li>
<li><p>You can see that ZIP Code like 94016 and 90001 shows significant sales activity.</p></li>
</ul></li>
<li><p><strong>Sales Distribution by City:</strong></p>
<ul>
<li><p>The count plot illustrates the distribution of sales across different cities, providing insights into regional sales performance.</p></li>
<li><p>Cities like SF and LA shows as being major sales hubs.</p></li>
</ul></li>
</ul>
</section>
<section id="product-sales-by-time" class="level4">
<h4 class="anchored" data-anchor-id="product-sales-by-time">5.5 Product Sales by Time</h4>
<p>Trends in the sales of top products over time highlight any seasonal patterns, aiding in inventory and marketing planning.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract top products for detailed analysis</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>top_product_list <span class="ot">&lt;-</span> top_products<span class="sc">$</span>Product</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>top_product_sales <span class="ot">&lt;-</span> sales <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Product <span class="sc">%in%</span> top_product_list)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Group sales by month-year and product</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>product_monthly_sales <span class="ot">&lt;-</span> top_product_sales <span class="sc">%&gt;%</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(MonthYear, Product) <span class="sc">%&gt;%</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Sales =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">'drop'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(Product, Sales, <span class="at">fill =</span> <span class="dv">0</span>)</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert from wide to long format for ggplot</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>product_monthly_sales_long <span class="ot">&lt;-</span> product_monthly_sales <span class="sc">%&gt;%</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(Product, Sales, <span class="sc">-</span>MonthYear)</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot sales of top products over time</span></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(product_monthly_sales_long, <span class="fu">aes</span>(<span class="at">x =</span> MonthYear, <span class="at">y =</span> Sales, <span class="at">color =</span> Product)) <span class="sc">+</span></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Monthly Sales Trend of Top Products"</span>, <span class="at">x =</span> <span class="st">"Month-Year"</span>, <span class="at">y =</span> <span class="st">"Number of Sales ($)"</span>) <span class="sc">+</span></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>() <span class="sc">+</span></span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DTC_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Monthly Sales Trend of Top Products:</strong></p>
<ul>
<li><p>The line plot shows how the sales of the top products vary over time, highlighting any seasonal patterns or trends for specific products.</p></li>
<li><p>Monthly sales trends of top products highlight seasonal preferences.</p></li>
<li><p>Increased sales of “Bose SoundSport Headphones” during summer months, possibly due to outdoor activities.</p></li>
</ul>
<hr>
</section>
<section id="conclusion" class="level4">
<h4 class="anchored" data-anchor-id="conclusion">Conclusion</h4>
<p>In this analysis, we explore the sales trends and patterns of Amazon’s technology products across various urban ZIP codes in 2019. Our dataset includes product names, quantities sold, prices, dates, and locations of the sales, as well as demographic information for the ZIP codes. Our goal is to uncover key insights about consumer behavior and market dynamics in different urban areas.</p>
<p>After cleaning and processing the data, we begin with a high-level overview and proceed with analyzing daily and monthly sales trends. We observe fluctuations in daily sales with noticeable peaks during certain periods, likely corresponding to events, holidays, or promotions. Monthly trends show a significant spike during the holiday season in December, indicating increased consumer spending during that time.</p>
<p>Next, we identify the top-selling products, such as “USB-C Charging Cable” and “Bose SoundSport Headphones,” which are key drivers of revenue. We then explore the relationship between sales and demographic factors, finding that higher sales volumes are associated with ZIP codes that have higher median household incomes and larger populations. This suggests that income levels and population density play significant roles in purchasing behavior.</p>
<p>We also visualize sales distribution across different ZIP codes and cities, highlighting areas with higher sales activity. Notably, San Francisco and Los Angeles emerge as major sales hubs. Finally, we analyze the sales trends of top products over time, uncovering seasonal preferences such as increased sales of “Bose SoundSport Headphones” during the summer months, likely due to outdoor activities.</p>
<p>In conclusion, our analysis reveals that sales patterns are influenced by income levels, population density, and seasonal trends. These insights can help Amazon optimize inventory management and tailor marketing strategies to different urban areas, ultimately enhancing sales performance and customer satisfaction.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>